# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateField(default=datetime.datetime(2017, 3, 20, 20, 1, 2, 257973))),
                ('value', models.FloatField(max_length=100)),
                ('to_date', models.DateField(default=datetime.datetime(2017, 3, 20, 20, 1, 2, 257973))),
                ('prise', models.FloatField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('items', models.ManyToManyField(related_name='Items', to='restaurant_manager.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 3, 20, 20, 1, 2, 257973))),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pass_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prise', models.FloatField(max_length=100)),
                ('duties', models.TextField()),
                ('requirements', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='func',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_manager.StaffFunc'),
        ),
    ]
